CREATE DATABASE IF NOT EXISTS einvoicing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE einvoicing;

CREATE TABLE IF NOT EXISTS countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    region VARCHAR(10) NOT NULL,
    country VARCHAR(120) NOT NULL UNIQUE,
    b2g ENUM('Mandatory','Voluntary','N/A') DEFAULT NULL,
    b2b ENUM('Mandatory','Voluntary','N/A') DEFAULT NULL,
    b2c ENUM('Mandatory','Voluntary','N/A') DEFAULT NULL,
    b2g_date VARCHAR(60) DEFAULT NULL,
    b2g_staggered ENUM('Y','N','N/A') DEFAULT NULL,
    b2b_date VARCHAR(60) DEFAULT NULL,
    b2b_staggered ENUM('Y','N','N/A') DEFAULT NULL,
    b2c_date VARCHAR(60) DEFAULT NULL,
    b2c_staggered ENUM('Y','N','N/A') DEFAULT NULL,
    non_local_suppliers ENUM('Y','N','N/A') DEFAULT NULL,
    digital_services_suppliers ENUM('Y','N','N/A') DEFAULT NULL,
    ap ENUM('Y','N','N/A') DEFAULT NULL,
    ar ENUM('Y','N','N/A') DEFAULT NULL,
    import_txn ENUM('Y','N','N/A') DEFAULT NULL,
    export_txn ENUM('Y','N','N/A') DEFAULT NULL,
    intra_eu_sales ENUM('Y','N','N/A') DEFAULT NULL,
    intra_eu_purchases ENUM('Y','N','N/A') DEFAULT NULL,
    zero_rated ENUM('Y','N','N/A') DEFAULT NULL,
    exempt ENUM('Y','N','N/A') DEFAULT NULL,
    e_reporting ENUM('Y','N','N/A') DEFAULT NULL,
    tax_authority VARCHAR(255) DEFAULT NULL,
    format VARCHAR(255) DEFAULT NULL,
    source TEXT DEFAULT NULL,
    status ENUM('pending','fetching','done','error') DEFAULT 'pending',
    last_updated TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO countries (region, country) VALUES
('EMEA','Albania'),('EMEA','Algeria'),('EMEA','Angola'),('AMER','Anguilla'),
('AMER','Antigua and Barbuda'),('AMER','Argentina'),('EMEA','Armenia'),
('AMER','Aruba'),('APAC','Australia'),('EMEA','Austria'),('EMEA','Azerbaijan'),
('AMER','Bahamas'),('EMEA','Bahrain, Kingdom of'),('APAC','Bangladesh'),
('AMER','Barbados'),('EMEA','Belgium'),('APAC','Bhutan'),('AMER','Bolivia'),
('AMER','Bonaire, Sint Eustatius and Saba (BES Islands)'),
('EMEA','Bosnia and Herzegovina'),('EMEA','Botswana'),('AMER','Brazil'),
('EMEA','Bulgaria'),('EMEA','Cabo Verde'),('APAC','Cambodia'),('EMEA','Cameroon'),
('AMER','Canada'),('EMEA','Chad'),('AMER','Chile'),('APAC','China Mainland'),
('AMER','Colombia'),('EMEA','Congo, Republic of the'),('AMER','Costa Rica'),
('EMEA','Cote D Ivoire (Ivory Coast)'),('EMEA','Croatia'),('AMER','Curacao'),
('EMEA','Cyprus'),('EMEA','Czech Republic'),
('EMEA','Democratic Republic of the Congo'),('EMEA','Denmark'),
('AMER','Dominican Republic'),('AMER','Ecuador'),('EMEA','Egypt'),
('AMER','El Salvador'),('EMEA','Equatorial Guinea'),('EMEA','Estonia'),
('EMEA','Eswatini'),('EMEA','Ethiopia'),('EMEA','European Union'),('APAC','Fiji'),
('EMEA','Finland'),('EMEA','France'),('EMEA','Georgia'),('EMEA','Germany'),
('EMEA','Ghana'),('EMEA','Greece'),('AMER','Guatemala'),('EMEA','Guinea'),
('AMER','Guyana'),('AMER','Honduras'),('EMEA','Hungary'),('APAC','India'),
('APAC','Indonesia'),('EMEA','Ireland, Republic of'),('EMEA','Isle of Man'),
('EMEA','Israel'),('EMEA','Italy'),('AMER','Jamaica'),('APAC','Japan'),
('EMEA','Jersey, Channel Islands'),('EMEA','Jordan'),('EMEA','Kazakhstan'),
('EMEA','Kenya'),('APAC','Korea, Republic of'),('EMEA','Kosovo'),('EMEA','Kuwait'),
('EMEA','Kyrgyzstan'),('APAC','Lao, Peoples Democratic Republic'),('EMEA','Latvia'),
('EMEA','Lebanon'),('EMEA','Lesotho'),('EMEA','Liechtenstein, Principality of'),
('EMEA','Lithuania'),('EMEA','Luxembourg'),('EMEA','Malawi'),('APAC','Malaysia'),
('APAC','Maldives'),('EMEA','Malta'),('EMEA','Mauritania'),('EMEA','Mauritius'),
('AMER','Mexico'),('EMEA','Moldova'),('APAC','Mongolia'),
('EMEA','Montenegro, Republic of'),('EMEA','Morocco'),('EMEA','Mozambique'),
('APAC','Myanmar'),('EMEA','Namibia'),('APAC','Nepal'),('EMEA','Netherlands'),
('APAC','New Zealand'),('AMER','Nicaragua'),('EMEA','Nigeria'),
('EMEA','North Macedonia'),('EMEA','Norway'),('EMEA','Oman'),('APAC','Pakistan'),
('AMER','Panama'),('APAC','Papua New Guinea'),('AMER','Paraguay'),('AMER','Peru'),
('APAC','Philippines'),('EMEA','Poland'),('EMEA','Portugal'),('AMER','Puerto Rico'),
('EMEA','Qatar'),('EMEA','Romania'),('EMEA','Rwanda'),
('AMER','Saint Kitts and Nevis'),('AMER','Saint Lucia'),
('AMER','Saint Vincent and the Grenadines'),('EMEA','Sao Tome and Principe'),
('EMEA','Saudi Arabia'),('EMEA','Senegal'),('EMEA','Serbia, Republic of'),
('APAC','Singapore'),('AMER','Sint Maarten'),('EMEA','Slovak Republic'),
('EMEA','Slovenia'),('EMEA','South Africa'),('EMEA','South Sudan'),('EMEA','Spain'),
('APAC','Sri Lanka'),('AMER','Suriname'),('EMEA','Sweden'),('EMEA','Switzerland'),
('APAC','Taiwan'),('EMEA','Tanzania'),('APAC','Thailand'),
('AMER','Trinidad and Tobago'),('EMEA','Tunisia'),('EMEA','Turkiye'),
('EMEA','Uganda'),('EMEA','Ukraine'),('EMEA','United Arab Emirates'),
('EMEA','United Kingdom'),('AMER','United States'),('AMER','Uruguay'),
('EMEA','Uzbekistan'),('AMER','Venezuela'),('APAC','Vietnam'),('EMEA','Zambia'),
('EMEA','Zimbabwe');
